//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalInfo
    {
        //[MaxLength(9, ErrorMessage = "לא קיים מספר זהות עם יותר מ9 ספרות")]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> NumberStreet { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        //[RegularExpression(@"^[0-9]{0,9}$", ErrorMessage = "יכול להכיל 9 ספרות בלבד")]
        public string Phone { get; set; }
        //[RegularExpression(@"^[0-9]{0,10}$", ErrorMessage = "יכול להכיל 10 ספרות בלבד")]
        public string Cellphone { get; set; }
        public Nullable<System.DateTime> VacDate1 { get; set; }
        public Nullable<System.DateTime> VacDate2 { get; set; }
        public Nullable<System.DateTime> VacDate3 { get; set; }
        public Nullable<System.DateTime> VacDate4 { get; set; }
        public string VacMaker1 { get; set; }
        public string VacMaker2 { get; set; }
        public string VacMaker3 { get; set; }
        public string VacMaker4 { get; set; }
        public Nullable<System.DateTime> SickDate { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
    }
}
